export { default as Paus } from './paus'
export { default as Ouros } from './ouros'
export { default as Copas } from './copas'
export { default as Espadas } from './espadas'
export { default as Profile } from './profile'
